services:
      backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        ports:
          - "3001:3001"
        environment:
          - NODE_ENV=production
          - BACKEND_PORT=3001
          - DB_HOST=db
          - DB_USER=root
          - DB_PASSWORD=1234
          - DB_NAME=web
          - DB_PORT=3306
        depends_on:
          - db
        restart: always 
        networks:
          - movie-network
        volumes:
          - ./public:/app/public
          

      frontend:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "80:80"
        environment:
          - REACT_APP_API_URL=${REACT_APP_API_URL}
        depends_on:
          - backend
        networks:
          - movie-network

      db:
        image: mysql:8.0
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "1234" 
          MYSQL_DATABASE: web
          MYSQL_ROOT_HOST: "%"
        volumes:
          - db-data:/var/lib/mysql
          - ./mysql-init-scripts:/docker-entrypoint-initdb.d
        ports:
          - "3307:3306"
        networks:
          - movie-network

networks:
      movie-network:
        driver: bridge

volumes:
      db-data: